name: Auditoria Quimica DMR4

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Validar Base de Datos y Script
      run: |
        # Forzamos la lectura en UTF-8 para evitar errores con tildes y eñes
        python -c "import json; json.load(open('preguntas_quimica.json', encoding='utf-8'))"
        # Verificamos que el script no tenga errores de sintaxis
        python -m py_compile main.py

