name: Auditoria Quimica DMR4

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Validar JSON y Script
      run: |
        python -c "import json; json.load(open('preguntas_quimica.json'))"
        python main.py <<EOF
        
        EOF
